name: 构建 CloudflareSpeedTest
on:  
  workflow_dispatch:   # 允许手动触发

jobs:  
  build:  
    name: 构建  
    runs-on: ubuntu-latest  

    steps:  
      - name: 检出代码  
        uses: actions/checkout@v4  

      - name: 删除旧版本
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 0  # 设置为 0 表示删除所有旧版本
          delete_tags: true  # 同时删除关联的标签
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 设置 Go 环境  
        uses: actions/setup-go@v5
        with:  
          go-version: '1.16'  

      - name: 构建所有平台  
        run: |  
          # 创建构建目录和存储目录
          mkdir -p build
          mkdir -p binaries/linux/{amd64,386,arm64,arm,mips,mipsle}
          mkdir -p binaries/windows/{amd64,386}
          mkdir -p binaries/darwin/{amd64,arm64}

          # Linux  
          # AMD64  
          env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o CloudflareST
          tar -czf build/CloudflareST_linux_amd64.tar.gz CloudflareST
          cp CloudflareST binaries/linux/amd64/CloudflareST
          rm CloudflareST
          # 386  
          env GOOS=linux GOARCH=386 go build -ldflags="-s -w" -o CloudflareST
          tar -czf build/CloudflareST_linux_386.tar.gz CloudflareST
          cp CloudflareST binaries/linux/386/CloudflareST
          rm CloudflareST
          # ARM64  
          env GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o CloudflareST
          tar -czf build/CloudflareST_linux_arm64.tar.gz CloudflareST
          cp CloudflareST binaries/linux/arm64/CloudflareST
          rm CloudflareST
          # ARM  
          env GOOS=linux GOARCH=arm GOARM=7 go build -ldflags="-s -w" -o CloudflareST
          tar -czf build/CloudflareST_linux_arm.tar.gz CloudflareST
          cp CloudflareST binaries/linux/arm/CloudflareST
          rm CloudflareST
          # MIPS  
          env GOOS=linux GOARCH=mips GOMIPS=softfloat go build -ldflags="-s -w" -o CloudflareST
          tar -czf build/CloudflareST_linux_mips.tar.gz CloudflareST
          cp CloudflareST binaries/linux/mips/CloudflareST
          rm CloudflareST
          # MIPSLE  
          env GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -ldflags="-s -w" -o CloudflareST
          tar -czf build/CloudflareST_linux_mipsle.tar.gz CloudflareST
          cp CloudflareST binaries/linux/mipsle/CloudflareST
          rm CloudflareST

          # Windows  
          # AMD64  
          env GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o CloudflareST.exe
          tar -czf build/CloudflareST_windows_amd64.tar.gz CloudflareST.exe
          cp CloudflareST.exe binaries/windows/amd64/CloudflareST.exe
          rm CloudflareST.exe
          # 386  
          env GOOS=windows GOARCH=386 go build -ldflags="-s -w" -o CloudflareST.exe
          tar -czf build/CloudflareST_windows_386.tar.gz CloudflareST.exe
          cp CloudflareST.exe binaries/windows/386/CloudflareST.exe
          rm CloudflareST.exe

          # macOS  
          # AMD64  
          env GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o CloudflareST
          tar -czf build/CloudflareST_darwin_amd64.tar.gz CloudflareST
          cp CloudflareST binaries/darwin/amd64/CloudflareST
          rm CloudflareST
          # ARM64  
          env GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o CloudflareST
          tar -czf build/CloudflareST_darwin_arm64.tar.gz CloudflareST
          cp CloudflareST binaries/darwin/arm64/CloudflareST
          rm CloudflareST

      - name: 安装 UPX  
        run: |  
          sudo apt-get update  
          sudo apt-get install -y upx  

      - name: 使用 UPX 压缩二进制文件  
        run: |  
          cd build
          mkdir temp
          for file in *.tar.gz; do
            tar -xzf "$file" -C temp
            if [ -f "temp/CloudflareST" ]; then
              upx --best "temp/CloudflareST" || true
              tar -czf "$file" -C temp CloudflareST
            elif [ -f "temp/CloudflareST.exe" ]; then
              upx --best "temp/CloudflareST.exe" || true
              tar -czf "$file" -C temp CloudflareST.exe
            fi
            rm -rf temp/*
          done
          rm -rf temp

      - name: 生成 SHA256 校验和  
        run: |  
          cd build  
          sha256sum * > sha256sum.txt  

      - name: 提交并推送更改
        if: success()
        run: |
          # 确保 binaries 目录存在
          if [ -d "binaries" ]; then
            # 配置 git
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            
            # 只添加 binaries 目录
            git add binaries/
            
            # 获取当前时间
            current_time=$(date '+%Y/%m/%d %H:%M:%S')
            
            # 尝试提交更改
            if git diff --staged --quiet; then
              echo "没有需要提交的更改"
            else
              # 提交更改
              git commit -m "Update binaries on ${current_time}"
              
              # 设置远程仓库 URL
              git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
              
              # 拉取最新更改并变基
              git pull --rebase
              
              # 推送更改
              git push
            fi
          else
            echo "binaries 目录不存在，跳过提交"
          fi

      - name: 上传构建产物  
        uses: actions/upload-artifact@v4
        with:  
          name: CloudflareST-构建产物  
          path: build/*  

      - name: 创建发布版本  
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'workflow_dispatch'  
        with:  
          tag_name: build-${{ github.run_number }}  
          name: 构建版本 ${{ github.run_number }}  
          draft: false  
          prerelease: false  
          files: |  
            build/*.tar.gz  
            build/sha256sum.txt  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
